spring:
  application:
    name: note-manager
  
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      leak-detection-threshold: 60000
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION

server:
  port: 8080
  
jwt:
  secret: ${JWT_SECRET}
  expiration: 3200000

logging:
  level:
    org.springframework.security: WARN
    note_manager: INFO
    org.hibernate: WARN
    com.zaxxer.hikari: WARN


admin:
  user:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    nombre: ${ADMIN_NOMBRE}
    apellido: ${ADMIN_APELLIDO}