spring:
  application:
    name: note-manager
  
  # Configuración de Base de Datos
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Configuración de JPA
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor
server:
  port: 8080
  
# Configuración JWT
jwt:
  secret: ${JWT_SECRET}
  expiration: 3200000  


logging:
  level:
    org.springframework.security: WARN
    note_manager: INFO
    org.hibernate: WARN